"""Make_workspace_id_required_and_update_foreign_key_constraints

Revision ID: 3cc16d4f8bbb
Revises: 54ffc5a9b833
Create Date: 2026-02-01 12:50:58.707755

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cc16d4f8bbb"
down_revision: Union[str, Sequence[str], None] = "54ffc5a9b833"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "files", "workspace_id", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    op.alter_column(
        "folders", "workspace_id", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    op.alter_column(
        "notes", "workspace_id", existing_type=sa.VARCHAR(length=36), nullable=False
    )
    op.alter_column(
        "workspace_user_association",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_constraint(
        op.f("workspaces_created_by_fkey"), "workspaces", type_="foreignkey"
    )
    op.create_foreign_key(None, "workspaces", "users", ["created_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workspaces", type_="foreignkey")
    op.create_foreign_key(
        op.f("workspaces_created_by_fkey"),
        "workspaces",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.alter_column(
        "workspace_user_association",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "notes", "workspace_id", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    op.alter_column(
        "folders", "workspace_id", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    op.alter_column(
        "files", "workspace_id", existing_type=sa.VARCHAR(length=36), nullable=True
    )
    # ### end Alembic commands ###
