"""Update required fields for storage backends

Revision ID: b14d95497d4f
Revises: 5bb5281de909
Create Date: 2026-01-31 15:28:39.601499

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b14d95497d4f"
down_revision: Union[str, Sequence[str], None] = "5bb5281de909"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.
    升级数据库架构：
    - 将 storage_backends 表的 workspace_id 字段设为必填
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "storage_backends",
        "workspace_id",
        existing_type=sa.VARCHAR(length=36),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.
    降级数据库架构：
    - 恢复 storage_backends 表的 workspace_id 字段为可选

    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "storage_backends",
        "workspace_id",
        existing_type=sa.VARCHAR(length=36),
        nullable=True,
    )
    # ### end Alembic commands ###
